#!/usr/bin/env node

const fs = require("fs");
const path = require("path");
const bson = require("bson");

const authority = {
    ca: Buffer.from(process.env.AUTH_CA).toString("base64"),
    key: Buffer.from(process.env.AUTH_KEY).toString("base64"),
    cert: Buffer.from(process.env.AUTH_CERT).toString("base64"),
};

const encoded = bson.serialize(authority);
const filename = path.resolve(__dirname, "authority");

fs.writeFileSync(filename, encoded);
